replicaCount: 1

image:
  repository: acrchistdev.azurecr.io/chist-report
  pullPolicy: Always
  tag: 'a211f71'

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "report-module"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8081

ingress:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8081
  initialDelaySeconds: 150
  periodSeconds: 15
  failureThreshold: 10

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8081
  initialDelaySeconds: 150
  periodSeconds: 15
  failureThreshold: 10

autoscaling:
  enabled: false

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

envFrom:
  - secretRef:
      name: secret-report
  - secretRef:
      name: rabbitmq-secret

env:
  - name: SERVER_PORT_REPORT
    value: "8081"
  - name: APP_UPLOAD_DIR
    value: "/tmp/uploads"

httpRoute:
  enabled: false
