replicaCount: 1

image:
  repository: acrchistdev.azurecr.io/chist-notification
  pullPolicy: Always
  tag: '6a44e1e'

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "notification-module"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8082

ingress:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8082
  initialDelaySeconds: 90
  periodSeconds: 15
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8082
  initialDelaySeconds: 90
  periodSeconds: 15
  failureThreshold: 5

autoscaling:
  enabled: false

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

envFrom:
  - secretRef:
      name: secret-notification
  - secretRef:
      name: rabbitmq-secret

env:
  - name: SERVER_PORT_NOTIFICATION
    value: "8082"

httpRoute:
  enabled: false
