ALTER TABLE users
    DROP COLUMN IF EXISTS bonus_multiplier,
    DROP COLUMN IF EXISTS verified_since,
    DROP COLUMN IF EXISTS admin_level,
    RENAME COLUMN password TO password_hash,
    RENAME COLUMN streak TO streak_days,
    ALTER COLUMN password_hash SET NOT NULL,
    ALTER COLUMN email SET NOT NULL,
    ALTER COLUMN username SET NOT NULL,
    ALTER COLUMN role SET NOT NULL DEFAULT 'USER',
    ALTER COLUMN points SET NOT NULL DEFAULT 0,
    ALTER COLUMN streak_days SET NOT NULL DEFAULT 0,
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN updated_at SET NOT NULL,
    ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS is_verified_user BOOLEAN NOT NULL DEFAULT FALSE,
    DROP CONSTRAINT IF EXISTS users_email_key,
    DROP CONSTRAINT IF EXISTS users_username_key,
    ADD CONSTRAINT users_email_unique UNIQUE (email),
    ADD CONSTRAINT users_username_unique UNIQUE (username);